# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QTableWidget, QTableWidgetItem, QWidget
import json


from FileRedirection import FileRedirection
from Verwaltung import Verwaltung


class Ui_GUI(QWidget):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.resize(551, 221)
        self.verticalLayoutWidget = QtWidgets.QWidget(GUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 50, 91, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("btnAnlegen")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("btnBearbeiten")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("btnLoeschen")
        self.verticalLayout.addWidget(self.pushButton)
        self.tableWidget = QtWidgets.QTableWidget(GUI)
        self.tableWidget.setGeometry(QtCore.QRect(120, 30, 401, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "File-Redirection-Manager"))
        self.pushButton_3.setText(_translate("GUI", "Anlegen"))
        self.pushButton_2.setText(_translate("GUI", "Bearbeiten"))
        self.pushButton.setText(_translate("GUI", "Löschen"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GUI", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GUI", "Source"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GUI", "Target"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GUI", "Dateityp"))
        
    def loadData(self):
        fr = FileRedirection("Test", "C:/Source", "C:/Target", "pdf")
        fr2 = FileRedirection("Test2", "C:/Source2", "C:/Target2", "pdf2")
        vManager = Verwaltung()
        data = vManager.getFileRedirections()
        list_data = data["FileRedirections"]
        self.tableWidget.setRowCount(len(data["FileRedirections"]))
        row = 0
        for i in range(len(list_data)):
            json_data = json.loads(list_data[i])
            print(json_data)
            print(row)
            self.tableWidget.setItem(row, 0, QTableWidgetItem(json_data['name']))
            self.tableWidget.setItem(row, 1, QTableWidgetItem(json_data['source']))
            self.tableWidget.setItem(row, 2, QTableWidgetItem(json_data['target']))
            self.tableWidget.setItem(row, 3, QTableWidgetItem(json_data['datatype']))
            row = row + 1
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI = QtWidgets.QWidget()
    ui = Ui_GUI()
    ui.setupUi(GUI)
    ui.loadData()
    GUI.show()
    sys.exit(app.exec_())
